import type { Incident } from './types';

export const allIncidents: Incident[] = [
  {
    id: 'INC001',
    title: 'Major Power Outage in Lusaka',
    description: 'A major power outage has affected the entire city center of Lusaka. Cause is currently unknown. Emergency services are on site.',
    location: 'Lusaka City Center, Lusaka, Zambia',
    status: 'In Progress',
    priority: 'High',
    dateReported: '2024-07-20T10:00:00Z',
    reporter: { name: 'Jane Doe', contact: 'jane.doe@email.com' },
    media: ['incident_photo_2'],
  },
  {
    id: 'INC002',
    title: 'Traffic Accident on Great East Road',
    description: 'A multi-vehicle collision has occurred on the Great East Road near Manda Hill. Traffic is heavily congested.',
    location: 'Great East Road, Lusaka, Zambia',
    status: 'Team Dispatched',
    priority: 'High',
    dateReported: '2024-07-20T09:30:00Z',
    reporter: { name: 'John Smith' },
    media: [],
  },
  {
    id: 'INC003',
    title: 'Water Pipe Burst in Kabwata',
    description: 'A main water pipe has burst, leading to flooding in the streets of Kabwata Site and Service. Water utility has been notified.',
    location: 'Kabwata Site and Service, Lusaka, Zambia',
    status: 'Verified',
    priority: 'Medium',
    dateReported: '2024-07-19T15:00:00Z',
    reporter: { name: 'Anonymous' },
    media: [],
  },
  {
    id: 'INC004',
    title: 'Suspicious Package at Levy Junction',
    description: 'A suspicious unattended bag has been reported near the entrance of Levy Junction Mall. The area has been cordoned off.',
    location: 'Levy Junction Mall, Lusaka, Zambia',
    status: 'In Progress',
    priority: 'High',
    dateReported: '2024-07-19T14:00:00Z',
    reporter: { name: 'Mall Security' },
    media: ['incident_photo_1'],
  },
  {
    id: 'INC005',
    title: 'Bushfire near Chilanga',
    description: 'A small bushfire has been spotted in the forest area south of Chilanga. Fire department has been dispatched.',
    location: 'Chilanga, Lusaka Province, Zambia',
    status: 'Resolved',
    priority: 'Medium',
dateReported: '2024-07-18T18:00:00Z',
    reporter: { name: 'Local Farmer' },
    media: [],
  },
  {
    id: 'INC006',
    title: 'Reported Robbery in Matero',
    description: 'A citizen reported a robbery at a local shop. Police have been notified and are investigating.',
    location: 'Matero, Lusaka, Zambia',
    status: 'Reported',
    priority: 'Medium',
dateReported: '2024-07-20T11:00:00Z',
    reporter: { name: 'Anonymous' },
    media: [],
  },
  {
    id: 'INC007',
    title: 'Fallen Tree Blocking Road',
    description: 'A large tree has fallen and is blocking traffic on Lumumba Road. City council has been contacted for removal.',
    location: 'Lumumba Road, Lusaka, Zambia',
    status: 'Verified',
    priority: 'Low',
    dateReported: '2024-07-20T08:00:00Z',
    reporter: { name: 'Peter Jones' },
    media: ['incident_photo_1', 'incident_photo_2'],
  },
];
